language: node_js

node_js:
  - node # latest nossde

before_script:
  - npm install -g --silent @angular/cli

script:
  - ng build --prod
  - npm install -g "@compodoc/compodoc"
  - compodoc -p tsconfig.json -s
notifications:
  email:
    on_failure: change
    on_success: change