language: node_js

node_js:
  - node # latest nossde

before_script:
  - npm install -g --silent @angular/cli

script:
  - ng build --prod
  - ng serve

notifications:
  email:
    on_failure: change
    on_success: change